--1) 송강 교수가 강의하는 과목을 검색한다
SELECT PNAME 교수명, CNAME 과목명
FROM PROFESSOR
NATURAL JOIN COURSE
WHERE PNAME = '송강';

--2) 화학 관련 과목을 강의하는 교수의 명단을 검색한다
SELECT PNAME 교수명단
FROM PROFESSOR
NATURAL JOIN COURSE
WHERE SECTION LIKE '%화학%';

--3) 학점이 2학점인 과목과 이를 강의하는 교수를 검색한다
SELECT CNAME 과목명, PNAME 교수명
FROM COURSE
NATURAL JOIN PROFESSOR
WHERE ST_NUM = 2;

--4) 화학과 교수가 강의하는 과목을 검색한다
SELECT PNAME 교수명, CNAME 과목명
FROM PROFESSOR
NATURAL JOIN COURSE
WHERE SECTION = '화학';

--5) 화학과 1학년 학생의 기말고사 성적을 검색한다
SELECT SNAME 학생이름, RESULT 기말성적
FROM SCORE
NATURAL JOIN STUDENT
WHERE MAJOR = '화학'
AND SYEAR = 1;

--6) 일반화학 과목의 기말고사 점수를 검색한다
SELECT CNAME 과목명, RESULT 기말성적
FROM SCORE
NATURAL JOIN COURSE
WHERE CNAME = '일반화학';

--7) 화학과 1학년 학생의 일반화학 기말고사 점수를 검색한다
SELECT SNAME 이름, RESULT 성적
FROM SCORE
JOIN COURSE USING (CNO)
JOIN STUDENT USING (SNO)
WHERE SYEAR = 1
AND MAJOR = '화학'
AND CNAME = '일반화학';

--8) 화학과 1학년 학생이 수강하는 과목을 검색한다
SELECT DISTINCT CNAME 수강과목
FROM SCORE
JOIN COURSE USING (CNO)
JOIN STUDENT USING (SNO)
WHERE SYEAR = 1
AND MAJOR = '화학';
