--1) DEPT 테이블의 모든 데이터를 삭제한 다음 ROLLBACK 과 COMMIT 을
--수행하고 결과를 확인하세요
SELECT *
FROM DEPT;

DELETE FROM DEPT;

ROLLBACK;

--2) EMP 와 DEPT 테이블의 모든 데이터를 삭제하세요
SELECT * FROM EMP;
SELECT * FROM DEPT;

DELETE FROM EMP;
DELETE FROM DEPT;

COMMIT;
ROLLBACK;

--3) EMP 테이블에 값들을 입력하세요
INSERT INTO EMP(ENO, ENAME, JOB, MGR, HDATE, SAL, COMM, DNO)
VALUES ('1001', '김연아', '개발', NULL, '1991-02-01', 4500,
        520, 10);
INSERT INTO EMP(ENO, ENAME, JOB, MGR, HDATE, SAL, COMM, DNO)
VALUES ('1002', '임꺽정', '회계', NULL, '1992-03-03', 4100,
        720, 20);
INSERT INTO EMP(ENO, ENAME, JOB, MGR, HDATE, SAL, COMM, DNO)
VALUES ('1003', '이만기', '씨름', NULL, '1999-12-12', 5500,
        820, 30);
INSERT INTO EMP(ENO, ENAME, JOB, MGR, HDATE, SAL, COMM, DNO)
VALUES ('1004', '강호동', '예능', NULL, '1991-11-09', 5500,
        620, 40);
ROLLBACK;
SELECT * FROM EMP;
COMMIT;

--4) EMP 테이블에 데이터를 입력하되 입사일에 날짜와 시간도 입력하세요        
SELECT SYSDATE
FROM DUAL;
--DATE 는 날짜 형식이 일치해야 입력된다
INSERT INTO EMP (ENO, ENAME, HDATE)
VALUES ('5001', '홍길동', '1991-01-03:07:15:25');

ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD:HH24:MI:SS';

SELECT * FROM EMP;

--5) 날짜 형식을 확인하고 TO_DATE() 를 사용해서 입력하라
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'YY-MM-DD';
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';

INSERT INTO EMP(ENO, ENAME, HDATE)
VALUES ('5002', '장나라', TO_DATE('1992-02-03:07:07:07',
'YYYY-MM-DD:HH24:MI:SS'));

SELECT * FROM EMP;

SELECT ENO, ENAME, TO_CHAR(HDATE, 'YYYY-MM-DD:HH24:MI:SS')
FROM EMP;

--6) 날짜에 적용되는 디폴트 값을 확인한다
ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD:HH24:MI:SS';
INSERT INTO EMP (ENO, HDATE)
VALUES('1', TO_DATE('2000', 'YYYY'));
INSERT INTO EMP (ENO, HDATE)
VALUES('3', TO_DATE('99', 'YY'));
INSERT INTO EMP (ENO, HDATE)
VALUES('4', TO_DATE('99', 'RR'));
COMMIT;
SELECT * FROM EMP;

--7) 김연아의 부서번호를 10번으로 수정하고 급여를 10%인상하세요
SELECT * FROM EMP;
UPDATE EMP SET DNO = '10', SAL = SAL * 1.1
WHERE ENAME = '김연아';
COMMIT;
ROLLBACK;