--1) 모든 학생의 성적을 4.5만점 기준으로 수정하세요
SELECT AVR FROM STUDENT;
UPDATE STUDENT SET AVR = (AVR/8)*9;

--2) 모든 교수의 부임일자를 100일 앞으로 수정하세요
SELECT HIREDATE FROM PROFESSOR;
UPDATE PROFESSOR SET HIREDATE = HIREDATE - 100;

--3) 화학과 2학년 학생의 정보를 삭제하세요
SELECT * FROM STUDENT;
DELETE FROM STUDENT
WHERE MAJOR = '화학'
AND SYEAR = 2;

--4) 조교수의 정보를 삭제하세요
SELECT * FROM PROFESSOR;
DELETE FROM PROFESSOR
WHERE ORDERS = '조교수';